[general]
import = [
  "themes/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "none"
padding = { x = 10, y = 10 }

[font]
normal = { family = "ComicShannsMono Nerd Font Mono", style = "Regular" }
bold = { family = "ComicShannsMono Nerd Font Mono", style = "Bold" }
italic = { family = "ComicShannsMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "ComicShannsMono Nerd Font Mono", style = "Bold Italic" }
size = 12.0
