[general]
import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "none"
padding = { x = 10, y = 10 }

[font]
normal = { family = "ComicShannsMono Nerd Font" }
size = 11.0
